								<header id="header">
								  <div class="row">
										<div class="col-4 col-12-medium">
											
										</div>
										<div class="col-4 col-12-medium">
											<p class="align-center">
												<a href="index.html" class="logo"><strong>Anderson Group</strong> <br>Molecular Engineering</a>
							  				</p>	
										</div>
										<div class="col-4 col-12-medium">
											<ul class="icons">
												<li><a href="https://twitter.com/HLAGroupOx" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
												<li><a href="#" class="icon brands fa-facebook"><span class="label">Oxford</span></a></li>
											</ul>
										</div>
									</div>
								</header>