<div class="privacy-banner">
  <div>
    <p>
      It seems that you are accessing this site using Internet Explorer. Please consider changing to a modern browser.
      <a class="button primary banner-accept" href="#">Accept</a>
      <a href="https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge">Learn more</a>
    </p>
  </div>
</div>

<script defer src="/assets/js/ie-banner.js"></script>