					<div id="sidebar">
						<div class="inner">						

							<!-- Menu -->
						  <nav id="menu">
							  		<p class="align-center">
										<a href="https://www.chem.ox.ac.uk/"><img class="lazyload oxlogo" data-src="/images/oxlogo_square.svg" alt="Oxford Logo" /></a>
							  		</p>

									<header class="major">
										<h2>Menu</h2>
									</header>
									<ul>
										<li><a href="/index.shtml">Homepage</a></li>
										<li><a href="https://www.chem.ox.ac.uk/people/harry-anderson?filter_types-2626476[]=&filter_series-2626476[]=">Research</a></li>
										<li>
											<span class="opener">Publications</span>
											<ul>
												<li><a href="/publications/current.shtml">2021-present</a></li>
												<li><a href="/publications/2020.shtml">2016-2020</a></li>
												<li><a href="/publications/2015.shtml">2011-2015</a></li>
												<li><a href="/publications/2010.shtml">2006-2010</a></li>
												<li><a href="/publications/2005.shtml">2001-2005</a></li>
												<li><a href="/publications/2000.shtml">1996-2000</a></li>
												<li><a href="/publications/1995.shtml">1989-1995</a></li>
												<li><a href="/publications/theses.shtml">Theses</a></li>
											</ul>
										</li>
										<li>
											<span class="opener">The Group</span>
											<ul>
												<li><a href="/group/harry.shtml">Meet Harry</a></li>
												<li><a href="/group.shtml">Current Members</a></li>
												<li><a href="/photos.shtml">Social Photo Gallery</a></li>
												<li><a href="/alumni.shtml">Alumni</a></li>
											</ul>
										</li>
										<li>
											<span class="opener">Facilities</span>
											<ul>
												<li><a href="/equipment.shtml">Equipment</a></li>
												<li><a href="https://www.chem.ox.ac.uk">Oxford Chemistry</a></li>
											</ul>
										</li>
										<li><a href="/talks.shtml">Video Talks</a></li>
										<li><a href="/vacancies.shtml">Join Us</a></li>
										<li><a href="/contact.shtml">Find Us</a></li>
										<li><a href="/collaborators.shtml">Our Collaborators</a></li>
										<li><a href="/erc.shtml">ERC Grant</a></li>
									</ul>
								</nav>

							<!-- Section -->
							<!-- EXAMPLE ENTRY -->
							<!-- For news requiring a single photo, the following template should be used -->
							<!--	<div class="row">
										<div class="col-4 col-12-small">
											<div class="grid">
												<a href="group/XXXX.shtml" class="image sidebar-picture"><img src="images/group/people/XXXX.jpg" alt="" /></a>
											</div>
										</div>
										<div class="col-8 col-12-small">
											<p class="sidebar">#SOME INTERESTING TEXT HERE# (#DATE#)</p>
										</div>
									</div> -->

							<!-- For news requiring multiple photos (up to 4), add additional <a> tags in the grid class. For example -->
							<!--	<div class="grid">
										<a href="group/XXXX.shtml" class="image sidebar-picture"><img src="images/group/people/XXXX.jpg" alt="" /></a>
										<a href="group/XXXX.shtml" class="image sidebar-picture"><img src="images/group/people/XXXX.jpg" alt="" /></a>
									</div> -->	
								<section>
									<header class="major">
									  <h2>Recent News</h2>
									</header>
									<hr class="sidebar">
									<div class="row">
										<div class="col-4 col-12-small">
											<div class="grid">
												<a href="group/sara.shtml" class="image sidebar-picture"><img src="images/group/people/sara.jpg" alt="" /></a>
												<!--<a href="group/chiara.shtml" class="image sidebar-picture"><img src="images/group/people/chiara.jpg" alt="" /></a>
												<a href="group/freddie.shtml" class="image sidebar-picture"><img src="images/group/people/freddie.jpg" alt="" /></a>-->
											</div>
										</div>
										<div class="col-8 col-12-small">
											<p class="sidebar">Welcome to our Part II students, <a href="group/sara.shtml">Sara Borghi</a>, Jack Pickering and Owen Kanisius. (October 2023)</p>
										</div>
									</div>
									<hr class="sidebar">
									<div class="row">
										<div class="col-4 col-12-small">
											<div class="grid">
												<a href="group/toby.shtml" class="image sidebar-picture"><img src="images/group/people/toby.jpg" alt="" /></a>
											</div>
										</div>
										<div class="col-8 col-12-small">
											<p class="sidebar">A warm welcome to, <a href="group/toby.shtml">Toby</a>, who is joining us as a Postdoctoral Research Assistant. (October 2023)</p>
										</div>
									</div>
									<hr class="sidebar">
									<div class="row">
										<div class="col-4 col-12-small">
											<div class="grid">
												<a href="group/keith.shtml" class="image sidebar-picture"><img src="images/group/people/keith.jpg" alt="" /></a>
											</div>
										</div>
										<div class="col-8 col-12-small">
											<p class="sidebar">Congratulations to <a href="group/keith.shtml">Keith Andrews</a>, who will be joining as a Lecturer at Durham University.  </p>
										</div>
									</div>
									<hr class="sidebar">
									<div class="row">
										<div class="col-4 col-12-small">
											<div class="grid">
												<a href="group/james.shtml" class="image sidebar-picture"><img src="images/group/people/james.jpg" alt="" /></a>
											</div>
										</div>
										<div class="col-8 col-12-small">
											<p class="sidebar">Congratulations to <a href="group/james.shtml">James Thomas</a>, who will be joining as faculty at Queen Mary University.  </p>
										</div>
									</div>
									<hr class="sidebar">
									<div class="row">
										<div class="col-4 col-12-small">
											<div class="grid">
												<a href="group/kavita.shtml" class="image sidebar-picture"><img src="images/group/people/kavita.jpg" alt="" /></a>
											</div>
										</div>
										<div class="col-8 col-12-small">
											<p class="sidebar">A warm welcome to, <a href="group/kavita.shtml">Kavita</a>, who is joining us as a Postdoctoral Research Assistant. (July 2023)</p>
										</div>
									</div>
									<hr class="sidebar">
									<div class="row">
										<div class="col-4 col-12-small">
											<div class="grid">
												<a href="group/lidao.shtml" class="image sidebar-picture"><img src="images/group/people/lidao.jpg" alt="" /></a>
												<a href="group/chiara.shtml" class="image sidebar-picture"><img src="images/group/people/chiara.jpg" alt="" /></a>
												<a href="group/freddie.shtml" class="image sidebar-picture"><img src="images/group/people/freddie.jpg" alt="" /></a>
											</div>
										</div>
										<div class="col-8 col-12-small">
											<p class="sidebar">Congratulations to <a href="group/lidao.shtml">Lidao Li</a>, <a href="group/chiara.shtml">Chiara Pigaiani</a> and <a href="group/freddie.shtml">Frederick Leslie</a> for handing in their Part-II thesis. (June 2023)</p>
										</div>
									</div>

									<ul class="actions center">
										<li><a href="/news.shtml" class="button">More</a></li>
									</ul>
								</section>
							
							<!-- Section -->
								<section>
									<header class="major">
										<h2>Get in touch</h2>
									</header>
									<p>For more of an idea of what we do, take a look at our publications. If you would like to contact Harry, please use the details below:</p>
									<ul class="contact">
										<li class="icon solid fa-envelope"><a href="mailto:harry.anderson@chem.ox.ac.uk">harry.anderson@chem.ox.ac.uk</a></li>
										<li class="icon solid fa-phone">+44 (0)1865 2 75704 </li>
										<li class="icon solid fa-flask">
											Department of Chemistry<br />
											University of Oxford<br />
											Chemistry Research Laboratory<br />
											Mansfield Road<br />
											Oxford OX1 3TA
										</li>
									</ul>
									<p>If you would like to come and work with us, have a read of our vacancies page.</p>
									<ul class="actions center">
										<li><a href="vacancies.shtml" class="button big">Learn More</a></li>
									</ul>
								</section> 

							<!-- Footer -->
								<footer id="footer">
									<p class="copyright">© Connor Patrick & the Harry Anderson Group. All rights reserved.</p>
									<dark-mode-toggle
								    	id="dark-mode-toggle-1"
										appearance="toggle"
								    	dark=""
								    	light=""
								    	remember="Remember"
										permanent="true"
									></dark-mode-toggle>
								</footer>

						</div>
					</div>