					<div id="sidebar">
						<div class="inner">						

							<!-- Menu -->
						  <nav id="menu">
							  		<p class="align-center">
										<a href="https://www.chem.ox.ac.uk/"><img class="lazyload oxlogo" data-src="/images/oxlogo_square.svg" alt="Oxford Logo" /></a>
							  		</p>

									<header class="major">
										<h2>Menu</h2>
									</header>
									<ul>
										<li><a href="/index.shtml">Homepage</a></li>
										<li><a href="http://research.chem.ox.ac.uk/harry-anderson.aspx">Research</a></li>
										<li>
											<span class="opener">Publications</span>
											<ul>
												<li><a href="/publications/current.shtml">2021-present</a></li>
												<li><a href="/publications/2020.shtml">2016-2020</a></li>
												<li><a href="/publications/2015.shtml">2011-2015</a></li>
												<li><a href="/publications/2010.shtml">2006-2010</a></li>
												<li><a href="/publications/2005.shtml">2001-2005</a></li>
												<li><a href="/publications/2000.shtml">1996-2000</a></li>
												<li><a href="/publications/1995.shtml">1989-1995</a></li>
												<li><a href="/publications/theses.shtml">Theses</a></li>
											</ul>
										</li>
										<li>
											<span class="opener">The Group</span>
											<ul>
												<li><a href="/group/harry.shtml">Meet Harry</a></li>
												<li><a href="/group.shtml">Current Members</a></li>
												<li><a href="/photos.shtml">Social Photo Gallery</a></li>
												<li><a href="/alumni.shtml">Alumni</a></li>
											</ul>
										</li>
										<li>
											<span class="opener">Facilities</span>
											<ul>
												<li><a href="/equipment.shtml">Equipment</a></li>
												<li><a href="https://www.chem.ox.ac.uk">Oxford Chemistry</a></li>
											</ul>
										</li>
										<li><a href="/vacancies.shtml">Join Us</a></li>
										<li><a href="/contact.shtml">Find Us</a></li>
										<li><a href="/collaborators.shtml">Our Collaborators</a></li>
									</ul>
								</nav>

							<!-- Section -->
							<!-- EXAMPLE ENTRY -->
							<!-- For news requiring a single photo, the following template should be used -->
							<!--	<div class="row">
										<div class="col-4 col-12-small">
											<a href="group/XXXX.shtml" class="image news"><img src="images/group/people/XXXX.jpg" alt="" /></a>
										</div>
										<div class="col-8 col-12-small">
											<p>#SOME_TEXT_HERE#. (#DATE#)</p>
										</div>
									</div> -->

							<!-- For news requiring a two photos, the following template should be used -->
							<!--	<div class="row">
										<div class="col-4 col-12-small">
										    <div class="column">
											    <a href="group/XXXX.shtml" class="image stack"><img src="images/group/people/XXXX.jpg" alt="" /></a>
											    <a href="group/XXXX.shtml" class="image stack"><img src="images/group/people/XXXX.jpg" alt="" /></a>
										    </div>
										</div>
										<div class="col-8 col-12-small">
											<p>#SOME_TEXT_HERE#. (#DATE#)</p>
										</div>
									</div> -->

								<section>
									<header class="major">
									  <h2>Recent News</h2>
									</header>

										<div class="row">
											<div class="col-4 col-12-small">
												<a href="group/joshua.shtml" class="image news"><img src="images/group/people/joshua.jpg" alt="" /></a>
											</div>
											<div class="col-8 col-12-small">
												<p>Welcome to <a href="group/joshua.shtml">Joshua Field</a> who is joining us for his second CDT rotation. (May 2021)</p>
											</div>
										</div>
										
										<hr class="sidebar">

										<div class="row">
											<div class="col-4 col-12-small">
												<a href="group/junfu.shtml" class="image news"><img src="images/group/people/junfu.jpg" alt="" /></a>
											</div>
											<div class="col-8 col-12-small">
												<p>Goodbye <a href="group/junfu.shtml">Junfu Tian</a> who is leaving us to continue his CDT rotation. (May 2021)</p>
											</div>
										</div>

										<hr class="sidebar">

										<div class="row">
											<div class="col-4 col-12-small">
												<a href="group/junfu.shtml" class="image news"><img src="images/group/people/junfu.jpg" alt="" /></a>
											</div>
											<div class="col-8 col-12-small">
												<p>A warm welcome to <a href="group/junfu.shtml">Junfu Tian</a> who is joining us for one of his CDT rotations. (February 2021)</p>
											</div>
										</div>

										<hr class="sidebar">
										
										<div class="row">
											<div class="col-4 col-12-small">
												<a href="group/lorel.shtml" class="image news"><img src="images/group/people/lorel.jpg" alt="" /></a>
											</div>
											<div class="col-8 col-12-small">
												<p>Congratulations to <a href="group/lorel.shtml">Lorel Scriven</a> for defending her thesis and leaving to join the Civil Service. (January 2021)</p>
											</div>
										</div>

										<hr class="sidebar">
										
										<div class="row">
											<div class="col-4 col-12-small">
												<a href="group/yueze.shtml" class="image news"><img src="images/group/people/yueze.jpg" alt="" /></a>
											</div>
											<div class="col-8 col-12-small">
												<p>Welcome to <a href="group/yueze.shtml">Yueze Gao</a>, joining us as a PostDoc. (January 2021)</p>
											</div>
										</div>

										<hr class="sidebar">

										<div class="row">
											<div class="col-4 col-12-small">
												<a href="group/michael.shtml" class="image news"><img class="lazyload" data-src="images/group/people/michael.jpg" alt="" /></a>
											</div>
											<div class="col-8 col-12-small">
												<p>Goodbye to <a href="group/michael.shtml">Michael Jir&aacute;sek</a>, starting a PDRA position in the <a href="https://wennemers.ethz.ch/">Helma Wennemers group</a>. (December 2020)</p>
											</div>
										</div>

										<hr class="sidebar">
									
									<ul class="actions center">
										<li><a href="/news.shtml" class="button">More</a></li>
									</ul>
								</section>
							
							<!-- Section -->
								<section>
									<header class="major">
										<h2>Get in touch</h2>
									</header>
									<p>For more of an idea of what we do, take a look at our publications. If you would like to contact Harry, please use the details below:</p>
									<ul class="contact">
										<li class="icon solid fa-envelope"><a href="mailto:harry.anderson@chem.ox.ac.uk">harry.anderson@chem.ox.ac.uk</a></li>
										<li class="icon solid fa-phone">+44 (0)1865 2 75704 </li>
										<li class="icon solid fa-home">
											Department of Chemistry<br />
											University of Oxford<br />
											Chemistry Research Laboratory<br />
											Mansfield Road<br />
											Oxford OX1 3TA
										</li>
									</ul>
									<p>If you would like to come and work with us, have a read of our vacancies page.</p>
									<ul class="actions center">
										<li><a href="vacancies.shtml" class="button big">Learn More</a></li>
									</ul>
								</section> 

							<!-- Footer -->
								<footer id="footer">
									<p class="copyright">© Connor Patrick & the Harry Anderson Group. All rights reserved.</p>
									<dark-mode-toggle
								    	id="dark-mode-toggle-1"
										appearance="toggle"
								    	dark=""
								    	light=""
								    	remember="Remember"
										permanent="true"
									></dark-mode-toggle>
								</footer>

						</div>
					</div>