					<div id="sidebar">
						<div class="inner">						

							<!-- Menu -->
						  <nav id="menu">
							  		<p class="align-center">
										<a href="https://www.chem.ox.ac.uk/"><img class="lazyload oxlogo" data-src="/images/oxlogo_square.svg" alt="Oxford Logo" /></a>
							  		</p>

									<header class="major">
										<h2>Menu</h2>
									</header>
									<ul>
										<li><a href="/index.shtml">Homepage</a></li>
										<li><a href="http://research.chem.ox.ac.uk/harry-anderson.aspx">Research</a></li>
										<li>
											<span class="opener">Publications</span>
											<ul>
												<li><a href="/publications/current.shtml">2021-present</a></li>
												<li><a href="/publications/2020.shtml">2016-2020</a></li>
												<li><a href="/publications/2015.shtml">2011-2015</a></li>
												<li><a href="/publications/2010.shtml">2006-2010</a></li>
												<li><a href="/publications/2005.shtml">2001-2005</a></li>
												<li><a href="/publications/2000.shtml">1996-2000</a></li>
												<li><a href="/publications/1995.shtml">1989-1995</a></li>
												<li><a href="/publications/theses.shtml">Theses</a></li>
											</ul>
										</li>
										<li>
											<span class="opener">The Group</span>
											<ul>
												<li><a href="/group/harry.shtml">Meet Harry</a></li>
												<li><a href="/group.shtml">Current Members</a></li>
												<li><a href="/photos.shtml">Social Photo Gallery</a></li>
												<li><a href="/alumni.shtml">Alumni</a></li>
											</ul>
										</li>
										<li>
											<span class="opener">Facilities</span>
											<ul>
												<li><a href="/equipment.shtml">Equipment</a></li>
												<li><a href="https://www.chem.ox.ac.uk">Oxford Chemistry</a></li>
											</ul>
										</li>
										<li><a href="/vacancies.shtml">Join Us</a></li>
										<li><a href="/contact.shtml">Find Us</a></li>
										<li><a href="/collaborators.shtml">Our Collaborators</a></li>
									</ul>
								</nav>

							<!-- Section -->
							<!-- EXAMPLE ENTRY -->
							<!-- For news requiring a single photo, the following template should be used -->
							<!--	<div class="row">
										<div class="col-4 col-12-small">
											<div class="grid">
												<a href="group/XXXX.shtml" class="image sidebar-picture"><img src="images/group/people/XXXX.jpg" alt="" /></a>
											</div>
										</div>
										<div class="col-8 col-12-small">
											<p class="sidebar">#SOME INTERESTING TEXT HERE# (#DATE#)</p>
										</div>
									</div> -->

							<!-- For news requiring multiple photos (up to 4), add additional <a> tags in the grid class. For example -->
							<!--	<div class="grid">
										<a href="group/XXXX.shtml" class="image sidebar-picture"><img src="images/group/people/XXXX.jpg" alt="" /></a>
										<a href="group/XXXX.shtml" class="image sidebar-picture"><img src="images/group/people/XXXX.jpg" alt="" /></a>
									</div> -->	
								<section>
									<header class="major">
									  <h2>Recent News</h2>
									</header>

									<div class="row">
										<div class="col-4 col-12-small">
											<div class="grid">
												<a href="group/wenjun.shtml" class="image sidebar-picture"><img src="images/group/people/wenjun.jpg" alt="" /></a>
											</div>
										</div>
										<div class="col-8 col-12-small">
											<p class="sidebar">Goodbye <a href="group/wenjun.shtml">Wenjun</a>, we wish you the best for your future! (September 2021)</p>
										</div>
									</div>

									<hr class="sidebar">

									<div class="row">
										<div class="col-4 col-12-small">
											<div class="grid">
												<a href="group/jake.shtml" class="image sidebar-picture"><img src="images/group/people/jake.jpg" alt="" /></a>
												<a href="group/prakhar.shtml" class="image sidebar-picture"><img src="images/group/people/prakhar.jpg" alt="" /></a>
											</div>
										</div>
										<div class="col-8 col-12-small">
											<p class="sidebar">Welcome to our two new DPhil students, <a href="group/jake.shtml">Jake Holmes</a> and <a href="group/prakhar.shtml">Prakhar Gupta</a>! (September 2021)</p>
										</div>
									</div>
								
									<hr class="sidebar">

									<div class="row">
										<div class="col-4 col-12-small">
											<div class="grid">
												<a href="group/thea.shtml" class="image sidebar-picture"><img src="images/group/people/janko.jpg" alt="" /></a>
											</div>
										</div>
										<div class="col-8 col-12-small">
											<p class="sidebar">Welcome back to <a href="group/janko.shtml">Janko</a>, who is joining us for his DPhil. (September 2021)</p>
										</div>
									</div>
								
									<hr class="sidebar">
								
									<div class="row">
										<div class="col-4 col-12-small">
											<div class="grid">
												<a href="group/thea.shtml" class="image sidebar-picture"><img src="images/group/people/thea.jpg" alt="" /></a>
											</div>
										</div>
										<div class="col-8 col-12-small">
											<p class="sidebar">A warm welcome to <a href="group/thea.shtml">Th&eacute;a Toutoungy</a>, who is joining us for her Part II. (September 2021)</p>
										</div>
									</div>
								
									<hr class="sidebar">
								
									<div class="row">
										<div class="col-4 col-12-small">
											<div class="grid">
												<a href="group/wenjun.shtml" class="image sidebar-picture"><img src="images/group/people/wenjun.jpg" alt="" /></a>
											</div>
										</div>
										<div class="col-8 col-12-small">
											<p class="sidebar">Congratulations to <a href="group/wenjun.shtml">Wenjun Xu</a> for submitting his thesis! (June 2021)</p>
										</div>
									</div>
								
									<hr class="sidebar">
								
									<div class="row">
										<div class="col-4 col-12-small">
											<div class="grid">
												<a href="group/steffen.shtml" class="image sidebar-picture"><img src="images/group/people/steffen.jpg" alt="" /></a>
											</div>
										</div>
										<div class="col-8 col-12-small">
											<p class="sidebar">Goodbye to <a href="group/steffen.shtml">Steffen Woltering</a> who is starting at Technische Universit&auml;t Dresden. We wish you the best with your future! (June 2021)</p>
										</div>
									</div>
									
									<hr class="sidebar">
										
									<ul class="actions center">
										<li><a href="/news.shtml" class="button">More</a></li>
									</ul>
								</section>
							
							<!-- Section -->
								<section>
									<header class="major">
										<h2>Get in touch</h2>
									</header>
									<p>For more of an idea of what we do, take a look at our publications. If you would like to contact Harry, please use the details below:</p>
									<ul class="contact">
										<li class="icon solid fa-envelope"><a href="mailto:harry.anderson@chem.ox.ac.uk">harry.anderson@chem.ox.ac.uk</a></li>
										<li class="icon solid fa-phone">+44 (0)1865 2 75704 </li>
										<li class="icon solid fa-flask">
											Department of Chemistry<br />
											University of Oxford<br />
											Chemistry Research Laboratory<br />
											Mansfield Road<br />
											Oxford OX1 3TA
										</li>
									</ul>
									<p>If you would like to come and work with us, have a read of our vacancies page.</p>
									<ul class="actions center">
										<li><a href="vacancies.shtml" class="button big">Learn More</a></li>
									</ul>
								</section> 

							<!-- Footer -->
								<footer id="footer">
									<p class="copyright">© Connor Patrick & the Harry Anderson Group. All rights reserved.</p>
									<dark-mode-toggle
								    	id="dark-mode-toggle-1"
										appearance="toggle"
								    	dark=""
								    	light=""
								    	remember="Remember"
										permanent="true"
									></dark-mode-toggle>
								</footer>

						</div>
					</div>